/**;
* Complete NPC Definitions for The Gilded Griffin Tavern;
* 15 Unique NPCs with detailed backstories, personalities, and reward systems;
*/;
const getAllNPCs = () => {;
return {;
barkeep: {;
name: "Marcus Blackwater",;
appearance: "Middle-aged man with a scarred face and weary eyes that have seen too much",;
personality: "worldly, cynical, but secretly cares for regular patrons",;
backstory: "Former captain who lost his entire unit at the Siege of Blackwater. Now runs this tavern as a sanctuary for lost souls.",;
location: "Behind the bar, cleaning glasses with practiced motions",;
dialog: {;
greeting: "Welcome to the Gilded Griffin. What brings you to my establishment? Drink, food, or trouble?",;
paths: {;
room: {;
text: "I need a room for the night",;
response: "20 silver coins. Breakfast included at dawn. No weapons upstairs - house rules.",;
followUp: ["Ask about other guests", "Request special arrangements", "Negotiate price"];
},;
rumors: {;
text: "Any interesting news?",;
response: "News travels fast in a tavern... for the right price. Northern roads are bandit territory. The king's guard is recruiting. And old man Hemlock's daughter went missing last week.",;
followUp: ["Buy information (10 gold)", "Ask about bandits", "Ask about missing girl"];
};
};
},;
rewards: {;
roomKey: { condition: "20 silver", item: "Room Key", effect: "Access private quarters + hidden treasure under floorboard" },;
information: { condition: "10 gold", item: "Tavern Rumors", effect: "Unlock 3 new quest opportunities" };
};
},;
mercCaptain: {;
name: "Valeria Stormblade",;
appearance: "Tall woman with silver-streaked black hair and a network of scars that tell stories",;
personality: "professional, no-nonsense, honor-bound, secretly lonely",;
backstory: "Exiled Countess of Stormwind. Her family was betrayed by her uncle who usurped their lands. She now leads the Silver Blades mercenary company.",;
location: "Large corner table with 4 armed guards, strategic overview of the tavern",;
dialog: {;
greeting: "You approach my table deliberately. Either you're very brave, very foolish, or very skilled. Which is it?",;
paths: {;
join: {;
text: "I want to hire your company",;
response: "My blades don't come cheap. 500 gold per month for five of my best. We escort caravans, guard nobles, hunt monsters, and... solve problems.",;
followUp: ["Negotiate price", "Ask about current contracts", "Request specific mercenary"];
},;
recruit: {;
text: "I want to join you",;
response: "Prove your worth. Bring me the head of the goblin chief in the western caves, or survive the haunted forest alone.",;
followUp: ["Ask about goblin chief", "Ask about haunted forest", "Request different test"];
};
};
},;
rewards: {;
mercenaries: { condition: "500 gold", item: "5 Silver Blades", effect: "Elite combat followers with special abilities" },;
recruitment: { condition: "quest completion", item: "Silver Blade Membership", effect: "Join mercenary company + free equipment" };
};
},;
rogue: {;
name: "Silas Shadowhand",;
appearance: "Slender man in dark leather that seems to absorb light, constantly scanning with practiced eyes",;
personality: "cautious, sarcastic, professional, seeking redemption",;
backstory: "Former master thief of the Shadow Guild. Stole evidence the guild master works for the enemy. Now in hiding, using his skills for good... when the price is right.",;
location: "Shadowy corner booth, back to wall, facing all entrances",;
dialog: {;
greeting: "Keep your voice down. Some conversations attract the wrong kind of attention. You have 30 seconds before I disappear.",;
paths: {;
theft: {;
text: "I need something acquired... discreetly",;
response: "Acquisition is my specialty. What's the target? Where is it? What security? And what's your budget?",;
followUp: ["Describe target", "Ask about prices", "Request references"];
},;
training: {;
text: "Teach me your ways",;
response: "The shadows don't teach just anyone. Pick my pocket without me noticing, or steal the barkeep's prize bottle.",;
followUp: ["Attempt to pickpocket", "Ask about bottle", "Offer different payment"];
};
};
},;
rewards: {;
lockpick: { condition: "100 gold", item: "Master Lockpick Set", effect: "Open any lock + bonus to stealth" },;
map: { condition: "200 gold", item: "Secret Tunnel Map", effect: "Access to underground network" };
};
},;
alchemist: {;
name: "Elara Nightshade",;
appearance: "Young woman with stained fingers, wild hair, and eyes that glow faintly in the dark",;
personality: "brilliant, eccentric, morally flexible, obsessed with discovery",;
backstory: "Expelled from the Royal Academy for unethical experiments - trying to create the philosopher's stone using unconventional ingredients.",;
location: "Small table covered in bubbling vials and strange apparatus",;
dialog: {;
greeting: "Don't touch anything unless you want to grow extra limbs. My experiments are unpredictable.",;
paths: {;
potions: {;
text: "What potions do you have?",;
response: "Healing, mana, strength. But my specialty? Invisibility, truth serum, shapeshifting... with interesting side effects.",;
followUp: ["Buy standard potions", "Ask about specialty potions", "Inquire about side effects"];
},;
ingredients: {;
text: "I have rare ingredients",;
response: "Dragon scales, phoenix feathers, demon blood? Each combination creates different effects. Some are explosive.",;
followUp: ["Show ingredients", "Ask about combinations", "Request specific potion"];
};
};
},;
rewards: {;
healing: { condition: "50 gold", item: "3 Super Healing Potions", effect: "Full health restoration + cure poison" },;
poison: { condition: "500 gold + rare ingredients", item: "Undetectable Poison", effect: "Eliminate any target without trace" };
};
},;
mage: {;
name: "Theron Voidweaver",;
appearance: "Elderly man in worn robes, hands glow with faint magical energy",;
personality: "wise, paranoid, powerful, lonely",;
backstory: "Banished from the magic academy for practicing forbidden arts - specifically necromancy and dimension-walking.",;
location: "Isolated corner table with ancient tomes and floating crystals",;
dialog: {;
greeting: "The arcane flows differently around you. You have potential... or problems. Which is it?",;
paths: {;
magic: {;
text: "Teach me magic",;
response: "Magic demands sacrifice. What are you willing to give up? Your memories? Your youth? Your ability to feel pain?",;
followUp: ["Offer sacrifice", "Ask about alternatives", "Request specific spell"];
},;
artifact: {;
text: "I need an enchanted item",;
response: "Power comes with cost. Weapons, armor, trinkets - what enchantment do you seek? Fire, ice, lightning, or something... forbidden?",;
followUp: ["Request weapon enchantment", "Ask about forbidden enchantments", "Negotiate price"];
};
};
},;
rewards: {;
spellbook: { condition: "sacrifice + 100 gold", item: "Basic Spellbook", effect: "Learn 3 new spells" },;
enchantment: { condition: "200 gold + rare item", item: "Enchanted Weapon", effect: "Magical damage + special ability" };
};
},;
broker: {;
name: "Isabella Cipher",;
appearance: "Elegant woman in fine clothes, eyes miss nothing",;
personality: "manipulative, charming, always has an angle",;
backstory: "Former court scribe who discovered that information is more valuable than gold. Now trades secrets for power and profit.",;
location: "Private booth with papers and locked chests",;
dialog: {;
greeting: "Knowledge is power, and I happen to be in the business of empowerment. What secrets do you seek?",;
paths: {;
secrets: {;
text: "What secrets do you know?",;
response: "Everything has its price. Royal scandals, merchant conspiracies, hidden treasures. What's your budget for truth?",;
followUp: ["Pay for information", "Negotiate price", "Ask about specific topic"];
},;
contacts: {;
text: "I need to meet someone",;
response: "Connections are my currency. Nobles, criminals, mages, merchants - who are you trying to reach? Everyone has their price.",;
followUp: ["Name target", "Ask about prices", "Request introduction"];
};
};
},;
rewards: {;
blackmail: { condition: "300 gold", item: "Blackmail Material", effect: "Manipulate any NPC once" },;
contacts: { condition: "favor + 200 gold", item: "Contact List", effect: "Access to exclusive services" };
};
},;
bountyHunter: {;
name: "Graves Ironjaw",;
appearance: "Massive man with missing eye and iron-reinforced jaw",;
personality: "brutal, efficient, lives for the hunt",;
backstory: "Former prison guard who realized hunting criminals pays better than guarding them. Has personal vendetta against goblins.",;
location: "Wall table with bounty board and weapons display",;
dialog: {;
greeting: "You're still breathing. That means you're not on my list. Yet.",;
paths: {;
bounties: {;
text: "Show me the bounty board",;
response: "Dead or alive. Pay's better for dead, less paperwork. Currently seeking: goblin chief (200g), bandit leader (150g), rogue mage (500g - dangerous).",;
followUp: ["Accept goblin bounty", "Accept bandit bounty", "Ask about mage bounty"];
},;
partnership: {;
text: "Let's hunt together",;
response: "I work alone. Unless you can prove you're not dead weight. Show me you can handle yourself in a real fight.",;
followUp: "Accept challenge", "Offer different payment", "Back down";
};
};
},;
rewards: {;
bountyList: { condition: "free", item: "Current Bounties", effect: "3 quest opportunities" },;
weapon: { condition: "partnership + combat proof", item: "Bounty Hunter's Crossbow", effect: "Ranged combat advantage" };
};
},;
smuggler: {;
name: "Finn Blackheart",;
appearance: "Sleazy man with shifty eyes and nervous hands",;
personality: "greedy, paranoid, always looking for angle",;
backstory: "Former fisherman who discovered smuggling is more profitable than fishing. Knows all the secret routes in and out of the city.",;
location: "Dark corner near back entrance, constantly checking over shoulder",;
dialog: {;
greeting: "Psst. Looking for something... special? Off the books?",;
paths: {;
goods: {;
text: "What are you selling?",;
response: "Things that 'fell off boats'. Rare artifacts, exotic spices, forbidden texts, weapons. What's your budget?",;
followUp: ["View rare artifacts", "Ask about weapons", "Inquire about texts"];
},;
passage: {;
text: "I need discreet passage",;
response: "My boat goes where questions don't. City guards, royal navy, monster patrols - all avoid my routes. Where are we going?",;
followUp: ["Request city exit", "Ask about island passage", "Negotiate price"];
};
};
},;
rewards: {;
rareItem: { condition: "400 gold", item: "Rare Artifact", effect: "Unique magical item" },;
passage: { condition: "300 gold", item: "Smuggler's Route", effect: "Access to restricted areas" };
};
},;
healer: {;
name: "Sister Mary",;
appearance: "Kind-faced woman with healing hands and compassionate eyes",;
personality: "nurturing, wise, protective of the innocent",;
backstory: "Former temple healer who left the order to help those the church abandons. Has divine healing powers but questions church doctrine.",;
location: "Quiet table near the hearth, surrounded by herbs and healing supplies",;
dialog: {;
greeting: "You carry much pain. Let me help ease your burden.",;
paths: {;
healing: {;
text: "I'm injured",;
response: "Let me see your wounds. The gods gave me gifts to share. This may tingle a bit... divine healing is... intense.",;
followUp: ["Accept healing", "Ask about powers", "Offer donation"];
},;
blessing: {;
text: "Bless my journey",;
response: "May the light guide your path. But first, show me your heart is true. Help someone in need, or perform an act of selfless courage.",;
followUp: ["Request blessing now", "Ask about quest", "Offer different payment"];
};
};
},;
rewards: {;
healing: { condition: "free or donation", item: "Full Healing", effect: "Restore all health + cure conditions" },;
blessing: { condition: "good karma + quest", item: "Divine Blessing", effect: "Temporary stat boost + protection" };
};
},;
gambler: {;
name: "Lucky Leo",;
appearance: "Flashy dressed man with gold rings and a constant smile",;
personality: "charming, reckless, incredibly lucky",;
backstory: "Professional gambler who wins more than he should. Some say he made a deal with a luck demon, others say he's blessed. Never knows when to quit.",;
location: "Center table with cards, dice, and piles of coins",;
dialog: {;
greeting: "Care to test your luck? I'm feeling generous today. Your luck against mine.",;
paths: {;
gamble: {;
text: "Let's play a game",;
response: "Dice, cards, or coin? I'll give you 2:1 odds to start. But be warned - my luck has teeth. What are you wagering?",;
followUp: ["Play dice", "Play cards", "Wager valuable item"];
},;
investment: {;
text: "I want to invest in your luck",;
response: "My luck is always for sale. For the right price, I can 'share' my fortune with you. Temporarily, of course. What's your stake?",;
followUp: ["Invest gold", "Invest favor", "Invest valuable item"];
};
};
},;
rewards: {;
winnings: { condition: "gamble + luck", item: "Large Sum of Gold", effect: "200-1000 gold" },;
charm: { condition: "investment + 500 gold", item: "Lucky Charm", effect: "Improved luck in all endeavors" };
};
},;
forger: {;
name: "Master Thomas",;
appearance: "Stoic man with ink-stained fingers and perfect penmanship",;
personality: "perfectionist, professional, amoral",;
backstory: "Former royal scribe who discovered fake documents pay better than real ones. Can duplicate any seal, signature, or document perfectly.",;
location: "Back booth with writing supplies and samples of work",;
dialog: {;
greeting: "Papers are everything in this world. Identity, authority, freedom. What documents do you need?",;
paths: {;
forge: {;
text: "I need documents forged",;
response: "Official papers, personal letters, royal decrees. My work is perfect - indistinguishable from originals. What do you need?",;
followUp: ["Request royal decree", "Ask about identity papers", "Inquire about prices"];
},;
escape: {;
text: "I need to disappear",;
response: "New identity costs more. Birth certificate, travel papers, letters of reference. Complete disappearance requires eliminating your old records. What's your price for freedom?",;
followUp: ["Request new identity", "Ask about record elimination", "Negotiate complete package"];
};
};
},;
rewards: {;
documents: { condition: "150 gold", item: "Forged Documents", effect: "Access restricted areas + impersonate officials" },;
identity: { condition: "800 gold", item: "New Identity", effect: "Evade authorities + start fresh" };
};
},;
cartographer: {;
name: "Madame Elise",;
appearance: "Elderly woman with maps tattooed on her arms and wild eyes",;
personality: "eccentric, obsessed with unknown territories",;
backstory: "Explorer who went mad after discovering places that shouldn't exist - cities that move, forests that remember, mountains that aren't always there.",;
location: "Table covered in strange maps and drawing tools",;
dialog: {;
greeting: "Maps lie. They show what is, not what could be. What impossible thing are you seeking?",;
paths: {;
maps: {;
text: "I need maps of this region",;
response: "Standard maps are boring. I have maps of places that don't exist yet. Cities that will be, ruins that haven't fallen, treasures waiting to be buried.",;
followUp: ["View standard maps", "Ask about future maps", "Request treasure map"];
},;
expedition: {;
text: "I need a guide",;
response: "I guide those who seek the impossible. Into the Mad Forest, across the Shifting Sands, through the Mirror City. What impossible destination calls to you?",;
followUp: ["Request guide to Mad Forest", "Ask about Mirror City", "Seek different destination"];
};
};
},;
rewards: {;
treasureMap: { condition: "200 gold", item: "Ancient Treasure Map", effect: "Hidden treasure location" },;
route: { condition: "rare item + 300 gold", item: "Secret Route Map", effect: "Shortcut through dangerous territory" };
};
},;
weaponSmith: {;
name: "Gareth Ironforge",;
appearance: "Muscular dwarf with soot-covered face and massive hands",;
personality: "passionate about craft, honorable, seeks perfection",;
backstory: "Dwarven smith exiled for creating weapons that were too deadly. Seeks to forge the perfect weapon and redeem his honor.",;
location: "Table near forge entrance with weapon samples and tools",;
dialog: {;
greeting: "Every weapon tells a story. What story will yours tell? Glory, justice, revenge?",;
paths: {;
weapons: {;
text: "I need a weapon forged",;
response: "Steel sings to those who listen. Sword, axe, hammer, bow? What do you need it to do? Cut through armor? Strike with elemental force? Never miss?",;
followUp: ["Request sword", "Ask about elemental weapons", "Seek precision weapon"];
},;
upgrade: {;
text: "Upgrade my weapon",;
response: "Good steel can always be better. Show me what you carry. I can sharpen, balance, enchant, or completely reforge. Rare materials create rare weapons.",;
followUp: ["Show weapon", "Ask about enchantments", "Inquire about rare materials"];
};
};
},;
rewards: {;
weapon: { condition: "300 gold", item: "Masterwork Weapon", effect: "Combat advantage + durability" },;
upgrade: { condition: "weapon + rare materials + 500 gold", item: "Enchanted Upgrade", effect: "Magical abilities + elemental damage" };
};
},;
bard: {;
name: "Lyra Silverstrings",;
appearance: "Beautiful woman with lute and knowing smile",;
personality: "charismatic, mysterious, uses music to influence others",;
backstory: "Former court bard who knows too many royal secrets. Uses her music to gather information and influence events from the shadows.",;
location: "Small stage area, captivating audience with music",;
dialog: {;
greeting: "Every song holds a secret. Which one do you want to hear? The song can heal, harm, or reveal truth.",;
paths: {;
songs: {;
text: "Play me a song",;
response: "Songs of glory (boost courage), love (charm others), or tragedy (reveal hidden truths)? Each teaches something different. What do you need?",;
followUp: ["Request glory song", "Ask about love song", "Seek truth song"];
},;
secrets: {;
text: "What secrets do your songs hold?",;
response: "The royal court is full of secrets. Affairs, conspiracies, murders disguised as accidents. Some secrets are worth dying for. Others worth killing for. What's your budget for forbidden knowledge?",;
followUp: ["Pay for court secrets", "Ask about specific noble", "Request different information"];
};
};
},;
rewards: {;
song: { condition: "100 gold", item: "Influential Song", effect: "Persuade NPCs + charm effect" },;
secret: { condition: "500 gold", item: "Royal Secret", effect: "Leverage over nobles + plot advancement" };
};
},;
assassin: {;
name: "The Ghost",;
appearance: "Indistinguishable figure in gray cloak, face always hidden",;
personality: "silent, efficient, mysterious",;
backstory: "Unknown - some say they're not human, others that they're death incarnate. Never speaks, always completes contracts.",;
location: "Darkest corner, barely visible, appears and disappears mysteriously",;
dialog: {;
greeting: "......",;
paths: {;
contract: {;
text: "I need someone eliminated",;
response: "...... Names have prices. What's the name? Where are they? What protection? The more important the target, the higher the price.",;
followUp: ["Provide target name", "Ask about prices", "Request different method"];
},;
training: {;
text: "Teach me your ways",;
response: "...... Death's lessons are final. Are you ready to die? To kill? To become nothing? The training kills most students. The survivors become something else entirely.",;
followUp: ["Accept training", "Ask about survival rate", "Request different instruction"];
};
};
},;
rewards: {;
assassination: { condition: "1000 gold + target name", item: "Silent Elimination", effect: "Remove any target permanently" },;
stealth: { condition: "near-death experience + 800 gold", item: "Shadow Cloak", effect: "Become undetectable + assassination training" };
};
};
};
};
if (typeof module !== 'undefined' && module.exports) {;
module.exports = { getAllNPCs };
};
